Update from anestisb source (#1)
* Manual system deopt disable

Nougat support for bytecode deoptimization & repair is broken.
This commit is a temporarily (hopefully) solution to override the
default enabled deoptimization so that the rest of execution chain
of the script can be debugged / developed against other compatibility
issues with Nougat AOSP tags.

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* Reorder proprietary blobs merged list

Ensure that /vendor entries are placed before /system entries

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* Log messages edits

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* Individual targets for shared libraries

More info at https://github.com/anestisb/android-prepare-vendor/issues/21

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* [WIP] Prepare base for alternative repair method

Since de-optimization and repair via smali/basmali is broken
we seek alternative methods via ART oat utils. The idea is to start
dumping DEX from OAT rodata section, repair the checksum and
let the dex2oat do the offset recalculation work again when pre-opt
for AOSP build. Have partially being test and not sure that it works
across the border. We'll just give it a shot.

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* N5x blobs list update

Some apps under system partition have been moved from
/app to /priv-app

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* N5x remove 'libgps.utils' shared libs

Module is now available from AOSP source:
https://android.googlesource.com/platform/hardware/qcom/gps/+/android-7.0.0_r1/msm8994/utils/Android.mk#53

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* N5x remove libloc_api_v02

Module is currently available from AOSP Nougat branches

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* Bytecode whitelist common for all repair methods

Speed-up logic that skips repairing unnecessary bytecode is common
for all supported methods. The OATDUMP method is still WIP to ensure
it can work for supported devices.

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* N5x remove libloc_ds_api

Module is currently available from AOSP Nougat branches

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* N5x API-24 remove libloc_eng

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* Vendor shared libraries have priority

It has been noticed that AOSP defines some target modules
for shared libraries that are present in vendor partition blobs.

e.g.
build/core/base_rules.mk:183: *** vendor/htc/flounder: MODULE.TARGET.SHARED_LIBRARIES.libbt-vendor_32 already defined by hardware/broadcom/libbt.
build/core/ninja.mk:163: recipe for target 'out_userdebug_Linux_7.0.0_r1/sources/build-aosp_flounder.ninja' failed

As such for generated shared libraries modules that are
located under vendor partition ensure that they always
selected by using the LOCAL_OVERRIDES_PACKAGES
flag.

We need to investigate if that is desired for /system too
so that we can simplify some bits that are quite complex
for some devices (e.g. gps location libs for N5x).

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* Fix extension extract bug

When image was provided with "../" path
the extension was wrongly extracted.

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* Overrides not working as expected

We still can't avoid conflicting module names. As such
we can't blindly add an individual module target for all
shared libraries. We have to proceed with cherry picking.

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* Cherrypick individual modules shared libs

Continuing the effort to fix [1], it seems that we can't blindly
upgrade all shared libraries from PRODUCT_COPY_FILES
to individual modules. Most of the supported devices conflict
in multiple places for re-definitions. While most case can be
dealt with some override options some can't.

As such we have to proceed with shared libs cherrypicking
to indicate which libraries from the master blobs list should
be defined as a separate module.

For this purpose the generate-vendor script is taking an
additional argument with a txt file which contains such libs
for each target device. File templates are located under
devices root dir (same with proprietary blobs list) and will
be periodically be updated with the required dependencies.

First target is support for N5x.

[1] https://github.com/anestisb/android-prepare-vendor/issues/21

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* Revert "N5x blobs list update"

This reverts commit 358cff75b2db1b56bc3bce3053c42211c8329f20.

* Typo in repair method type

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* Update hostTools dir structure

Since we need to also push some lib shared objects
refactor dir structure to match bin / lib64 convention
that AOSP host tools expect.

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* More N5x shared libs

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* N5x remove lights.bullhead blob

Module is available in AOSP under:
device/lge/bullhead/liblight

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* N6p blobs list update

Some location shared libs are now available from AOSP
"device/huawei/angler/location"

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* Enable LOCAL_DEX_PREOPT for /system bytecode

Allow repaired bytecode from /system partition to be pre-optimized
if global DEX_PREOPT flag is set.

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* OATDUMP byte code repair method

More info at https://github.com/anestisb/android-prepare-vendor/issues/22

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* Update hostTools binaries

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* N6p shared libs for API-24

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* Disable shared libs module gen when no modules

Don't try generating module targets for shared libraries when
shared blobs list file is empty.

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* N5x shared libs list update

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* Fix undefined variable bug

If not shared libraries modules are selected for a
provided partition, PKGS array is not defined resulting
to a runtime error. Add a boolean flag to ensure that array
is iterated only when elements available.

We probably need to re-consider the way we want to use
dynamically appended arrays in bash to avoid such cases,
although for the time being leave it for a later clean-up.

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* Remove old signatures from repaired JARs/APKs

In Nougat release Google introduced a new APK signature format V2 [1].
Since some bits from repaired APKs might collide (whole thing seems to be
on a transition state at the moment) remove old signatures to ensure that build
chains picks-up a fresh copy to re-sign.

[1] https://source.android.com/security/apksigning/v2.html

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* Variable rename

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* Don't try to repair boot jars

So far none of the Nexus devices has a boot framework jar
that is not available from AOSP. As such, save up-time by
skipping them when iterating the byte code locations, since
boot jars will never be selected from proprietary blob lists
with the current status of Nexus devices.

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* Push oatdump Linux bin

We're still missing the lib64 deps build from AOSP host
targets. We need to isolate the ones required to run
oatdump tool and push only those, avoiding polluting the
repo with unnecessary libraries.

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* Remove debug code

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* Quiet JAR/APK signature deletion

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* Fix boot jars name blacklist bug

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* Remove some verbose log messages

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* Remove special skip for resource only JARs

Some framework jars have only resource data and no bytecode.
So far we were explicitly skipping them by name. Follow-up bytecode
detection logic is smart enough to identify such cases and skip them
automatically.

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* Script help message rename

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* Log message update

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* Relative paths for log messages

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* Shellcheck lint fixes

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* Never DEX preopt repaired APKs/JARs

Mitigate issue https://github.com/anestisb/android-prepare-vendor/issues/22#issuecomment-245216672

This effectively means that we instruct the build to not optimize
the repaired bytecode, just zipalign & resign them. As such the
bytecode will be optimized at device first boot. This was the only
option to circumvent "--abort-on-hard-verifier-error" without
modifying the AOSP default makefiles.

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* Fix Linux bin dir structure bug

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* Merge .gitignore files to simplify maintenance

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* Out of channel oatdump bin deps download

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* chmod txt list files

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* Low memory size warning

Fixes issue https://github.com/anestisb/android-prepare-vendor/issues/13

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* Typo

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* Revert "N5x remove lights.bullhead blob"

This reverts commit d233bc4975b5aca70862db6cf12d181f4249ef99.

* Revert "Revert "N5x remove lights.bullhead blob""

This reverts commit f45d1ba6a604746611577a3da54e08bd0bc697b8.

* Revert "N5x remove libloc_api_v02"

This reverts commit 14beaf5573e1b3568d36c54ee5d9aa7e116a74d9.

* Revert N5x libloc_ds_api

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* Update README

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* Update README

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* Sort proprietary blob list files

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* Edit comments & log messages

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* Re-enable LOCAL_OVERRIDES_PACKAGES

Individual shared libs targets from prebuilt should use that
flag to override potential AOSP definitions of same modules

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* N5x libloc_api_v02 cannot build from AOSP

We've satisfied the shared libraries dependencies, although
we're still missing the header includes. Try to override the
AOSP module with our own prebuilt.

```
device/lge/bullhead/location/loc_api/loc_api_v02/location_service_v02.h:78:10: fatal error: 'qmi_idl_lib.h' file not found
#include "qmi_idl_lib.h"
```

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* Remove LOCAL_OVERRIDES_PACKAGES

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* N6p update blob lists

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* N5x update blob lists

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* Additional BoardConfigVendor.mk flags

Since we might need to control some vendor board config flags
without editing the AOSP sources, expose an additional txt
configuration file from generate-vendor.sh script. All flags specified
in '--flags-list' file will be appended to generated 'BoardConfigVendor.mk'

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* Revert missing blobs for N5x / N6p

Since we fixed the missing dependencies issues by
effectively closing the AOSP QCOM location partial
sources, revert the required prebuilt shared libraries.

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* Typo fixes

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* README update

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* More README updates

Configuration files explained + more examples

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* Enable LOCAL_PROPRIETARY_MODULE

When individual library is located under /vendor set the
LOCAL_PROPRIETARY_MODULE, otherwise it will
be stored in the default /system out base.

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* Split bytecode files from master blobs list

In order to have better & easier control over the bytecode
archive files that we want to repair from factory & include,
separate them from the master blobs list file.

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* Optimize whitelist skips

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* Optimize configuration files logic

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* Typo fix

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* N6p update configuration files

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* Preserve all when cp unmodified APK/JAR

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* N6p blobs list update

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* Revert accidentally removed inner blacklist

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* Shellcheck lint fixes

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* drop root support

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* Allow MAC OS with 7z

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* OS X compatibility fixes

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* Quiet 7z extract

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* fdisk unnecessary to check

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* 7z verify minimum support version

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* Fix arg passing bug

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* Fix empty vendor config list file bug

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* Remove 7z special output directory

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* Fix size calculation bug from du output

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* Unnecessary escape bug

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* Replace readlink with sh-realpath

Since OS X doesn't have by default GNU readlink, avoid an
aliasing nightmare for greadlink brew/macports by providing
a self-contained implementation of realpath. Thanks to mkropat
for the implementation.

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* Replace 7z with fuse-ext2

7z wasn't respecting symbolic links and was breaking
part of the following vendor generation logic that was
relying into them being untouched. It has been replaced
with fuse-ext2. Cheers to @jduck for pointing it out.

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* umount / fusermount wrapping support

OSXFuse works with umount, while Linux FUSE works with
fusermount. Wrap around command based on HOST_OS

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* Remove local rsync copy

Improve speed by mounting fuse-ext2 directly to
expected mountpoint without performing a local
rsync copy from image file.

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* Extra modules config file

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* Beautify makefile

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* Replace mv with symlink

Since mount points are RO, just create a symbolic
link from original /system to repaired /system when
not repairing have been applied.

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* Fix ln out dir bug when no repair

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* Directory clean-up

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* Refactor java version check

Also only enable check when repairing bytecode
with oat2dex.jar method.

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* oatdump bytecode repair method for MAC

Push link with oatdump bin & deps zip compiled for OS X.

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* Place configs under separate dir

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* Fix OS X oatdump missing DYLD bug

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* N6p extra modules config typo

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* grep out comments from proprietary-blobs.txt

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* Fix JAVA_HOME set bug for MAC

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* Fix empty configs parsing bug

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* README update examples

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* N6p API-24 blobs config update

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* umount if previous run with -k for same target

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* N6p blobs config update

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* N5x/N6p enable dm-verity for /vendor

Fix for issue #25

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* Update README

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* Print error log if fust-ext2 fails

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* N5x config blobs update

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* Error handling bug fix

FACTORY_IMGS_DATA was unbound if very early
abort occurred (e.g. help screen or invalid arg).

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* Fix issue #28

https://github.com/anestisb/android-prepare-vendor/issues/28
Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* README update with FAQ

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* Comments update & typo

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* Check for non supported /vendor/priv-app repair

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* Improve fuse mount error check

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* README changelog update

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>

* Missing path normalization

Fixes issue #27

Signed-off-by: Anestis Bechtsoudis <anestis@census-labs.com>